data:
    training:
        dataset:
            name: CityscapesSequence
            transform:
                features:
                    name: Compose
                    transforms:
                        - name: PILToTensor
                        - name: Resize
                          kwargs:
                              size: [256, 512]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                targets: null
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: true
                pin_memory: true
    validation:
        dataset:
            name: CityscapesSequence
            transform:
                features:
                    name: Compose
                    transforms:
                        - name: PILToTensor
                        - name: Resize
                          kwargs:
                              size: [256, 512]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                targets: null
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: false
                pin_memory: true
    test:
        dataset:
            name: CityscapesSequence
            transform:
                features:
                    name: Compose
                    transforms:
                        - name: PILToTensor
                        - name: Resize
                          kwargs:
                              size: [256, 512]
                        - name: ToDtype
                          kwargs:
                              dtype: float32
                              scale: true
                targets: null
        dataloader:
            kwargs:
                batch_size: 64
                shuffle: false
                pin_memory: true
logging:
    tqdm:
        period: 10
